[build]
  pre_cmd = ["templ generate"]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  include_ext = ["go", "templ"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = [".*_templ\\.go"]

[log]
  main_only = true
